#!/bin/bash
# Redirigir la salida a un log para depuración
exec > >(tee /var/log/aurora-worker-setup.log|logger -t user-data -s 2>/dev/console) 2>&1

echo "Iniciando aprovisionamiento del Spark Worker..."

# 1. Actualizar repositorios e instalar dependencias
apt-get update -y
apt-get install -y openjdk-11-jdk wget tar

# 2. Descargar e instalar Apache Spark 3.5.1
cd /opt
wget https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz
tar -xvzf spark-3.5.1-bin-hadoop3.tgz
mv spark-3.5.1-bin-hadoop3 spark
rm spark-3.5.1-bin-hadoop3.tgz

# 3. Configurar variables de entorno globales
echo 'export SPARK_HOME=/opt/spark' >> /etc/profile.d/spark.sh
echo 'export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin' >> /etc/profile.d/spark.sh
source /etc/profile.d/spark.sh

# 4. Arrancar el servicio Worker apuntando a la IP del Master
/opt/spark/sbin/start-worker.sh spark://172.31.88.233:7077

echo "Spark Worker aprovisionado y arrancado con éxito."