#!/bin/bash
exec > >(tee /var/log/aurora-submit-setup.log|logger -t user-data -s 2>/dev/console) 2>&1

echo "Iniciando aprovisionamiento del Nodo Submit..."

# 1. Instalar Java y Python (necesario para PySpark)
apt-get update -y
apt-get install -y openjdk-11-jdk wget tar python3-pip

# 2. Descargar e instalar Apache Spark 3.5.1
cd /opt
wget https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz
tar -xvzf spark-3.5.1-bin-hadoop3.tgz
mv spark-3.5.1-bin-hadoop3 spark
rm spark-3.5.1-bin-hadoop3.tgz

# 3. Instalar PySpark para que coincida con la versión exacta
pip3 install pyspark==3.5.1

# 4. Configurar variables de entorno
echo 'export SPARK_HOME=/opt/spark' >> /etc/profile.d/spark.sh
echo 'export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin' >> /etc/profile.d/spark.sh

echo "Nodo Submit aprovisionado con éxito."